# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    format_listener:
        rules:
            - { path: ^/ , priorities: [ json, html ] , fallback_format: json  }

    exception:
        enabled: true
    view:
        view_response_listener: 'force'
        formats:
            json: true

#    body_converter:
#        enabled: true
#    view:
#        formats: { json: true, xml: false, rss: false }
#        view_response_listener:  true
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
#sensio_framework_extra:
#    view: { annotations: false }
#    request: { converters: true }
